config/routes.rb
Rails.application.routes.draw do
  #CRUD ROUTES

  # Read all b castles
  # verb  path             to   controller#controller_action
  # get '/bouncy_castles', to: 'bouncy_castles#index'
  # # Read 1 b castle
  # Always put the new action above the show!!!
  # get '/bouncy_castles/new', to: 'bouncy_castles#new' # new page for the empty form
  # get '/bouncy_castles/:id', to: 'bouncy_castles#show'
  # # Create a b castle
  # # 2 step process
  # post '/bouncy_castles', to: 'bouncy_castles#create' # create action actually creates the bouncy castle, when we click submit
  # # Update a castle
  # # 2 step process
  # get '/bouncy_castles/:id/edit', to: 'bouncy_castles#edit' #edit page for prefilled form
  # patch '/bouncy_castles/:id', to: 'bouncy_castles#update'
  # # Delete a castle
  # delete '/bouncy_castles/:id', to: 'bouncy_castles#destroy'

  resources :bouncy_castles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bouncy_castle.rb
class BouncyCastle < ApplicationRecord
  validates :name, :address, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bouncy_castles_controller.rb
class BouncyCastlesController < ApplicationController

  before_action :find_bouncy_castle, only: [:show, :edit, :update, :destroy]
  # before calling all these methods, call the find_bouncy_castle method first!

  def index # Read all
    @bouncy_castles = BouncyCastle.all
  end

  def show # Read 1
    # @bouncy_castle = BouncyCastle.find(params[:id])
    # raise
  end

  def new
    @bouncy_castle = BouncyCastle.new # Empty instance of the bouncy castle to display in the form
  end

  def create
    # raise
    bouncy_castle = BouncyCastle.new(bouncy_castle_params)
    bouncy_castle.save

    redirect_to bouncy_castle_path(bouncy_castle) # Redirect to the show page - same as saying bouncy_castle.id


    # OUR PARAMS LOOK LIKE THIS NOW

     # params = {
     #   bouncy_castle:
     #     {"name"=>"Fluffy Bouncy", "address"=>"Berlin", "rating"=>"4"}
     # }


    # TO CREATE A BOUNCY CASTLE WE WOULD DO  THIS

    # BouncyCastle.create(params[:bouncy_castle])

    # BUT WE NEED TO USE STRONG PARAMS SO ACTUALLY WE DO THIS

    # bouncy_castle = BouncyCastle.new(bouncy_castle_params)

  end

  def edit
    # @bouncy_castle = BouncyCastle.find(params[:id]) # Prefilled bouncy castle instance to display in the form
  end

  def update
    # bouncy_castle = BouncyCastle.find(params[:id]) # Prefilled bouncy castle instance to display in the form
    @bouncy_castle.update(bouncy_castle_params)

    redirect_to bouncy_castle_path(@bouncy_castle) # Redirect to the show page
  end

  def destroy
    # bouncy_castle = BouncyCastle.find(params[:id])
    @bouncy_castle.destroy

    redirect_to bouncy_castles_path
  end

  private

  # STRONG PARAMS
  def bouncy_castle_params # Whitelist your params, only the ones below will be admitted. To protect against malicious input injections into forms
    params.require(:bouncy_castle).permit(:name, :address, :rating)
  end

  def find_bouncy_castle
    @bouncy_castle = BouncyCastle.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bouncy_castles_helper.rb
module BouncyCastlesHelper
end

app/views/bouncy_castles/_form.html.erb
<div class="container">

<%= simple_form_for(@bouncy_castle) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

</div>

app/views/bouncy_castles/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/bouncy_castles/index.html.erb
<h1>BouncyCastles</h1>
<ul>
  <% @bouncy_castles.each do |castle| %>
  <li>  <%= link_to castle.name, bouncy_castle_path(castle) %>- <%= castle.address %> <%= '⭐️' * castle.rating %></li>
  <% end %>
</ul>


<%= link_to 'Add a new bouncy', new_bouncy_castle_path  %>

app/views/bouncy_castles/new.html.erb
<h1> Create a BouncyCastles</h1>

<%= render 'form' %>

<!-- OLD HTML FORM
<form action="/bouncy_castles" method="post">
  <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="name">Name</label>
  <input type="text" name="bouncy_castle[name]">
  <label for="address">Address</label>
  <input type="text" name="bouncy_castle[address]">
  <label for="rating">Rating</label>
  <input type="number" name="bouncy_castle[rating]">
  <input type="submit">
</form>
 -->

app/views/bouncy_castles/show.html.erb
<h1><%= @bouncy_castle.name %> </h1>
<h2><%= @bouncy_castle.address %> <%= '⭐️' * @bouncy_castle.rating %></h2>

<%= link_to 'Edit this castle', edit_bouncy_castle_path(@bouncy_castle)  %>

<%= link_to 'Delete', bouncy_castle_path(@bouncy_castle), method: :delete, data: {confirm: 'Are you sure you want to delete?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bouncybouncy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>